apiVersion: v1
kind: Service
metadata:
    name: my-service
    labels:
       app: myweb-service
spec:
    selector:
        env: production
    type: NodePort
    ports:
      - nodePort: 30000
        port: 81
        targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
       env: production
#    matchExpressions:
#      - { key: env,  operator: In,  values: [ production ] }
  template:
    metadata:
     name: myweb-pod
     labels:
       env: production
    spec:
      containers:
      - name: myweb-con
        image: vimal13/apache-webserver-php:v2